language: python
python:
   - "2.6"
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5-dev"
install: "pip install -r requirements.txt -e ."
before_script:
  - psql -c 'create user modsec;' -U postgres
  - psql -c 'create database modsec;' -U postgres
  - psql -c 'grant all privileges on database modsec to modsec;' -U postgres
script: nosetests
services:
  - postgresql
